name: Release CD

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        node-version: [ 18.x ]
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}

      # - name: Install Modules
      #   run: npm install

      # - name: Build Project
      #   run: npm run build

  Tests:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        node-version: [ 18.x ]
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}

      # - name: Install Modules
      #   run: npm install

      # - name: ESLint Test
      #   run: npm run lint

      # - name: Format Test
      #   run: npm run format


  Deploy:
    runs-on: ubuntu-latest
    needs: [ Tests, Build ]
    strategy: 
      matrix: 
        node-version: [ 18.x ]
        path: [ /root/.nvm/versions/node/v18.16.0/bin/ ]
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            set -e
            export PATH=$PATH:${{ matrix.path }}
            cd vnuk-brand || exit 1
            echo "Stopping pm2 process..."
            pm2 stop vnuk || exit 1
            echo "Pulling latest changes..."
            git pull || exit 1
            echo "Installing dependencies..."
            npm install || exit 1
            echo "Building application..."
            npm run build || exit 1
            echo "Restarting pm2 process..."
            pm2 restart vnuk || exit 1
          EOF
